var isPc=!0,user=null,page=0,itemHeight=390,columns=Math.floor($(window).width()/200);5>columns&&(columns=5);try{$(".wrap").width(200*columns-10),$(".home_treelist").width(200*columns),$(".group_treelist").width(200*(columns-1))}catch(a){}0<$("#userlist").length&&columns--;var pageItems=Math.ceil($(window).height()/itemHeight)*columns,isLoading=!1,isEnd=!1,qrcodeTicket,isLogin=!1;
function urlRequest(a){return(a=RegExp("[?&]"+a+"=([^&]*)").exec(window.location.search))&&decodeURIComponent(a[1].replace(/\+/g," "))}function valueTrim(a){return $(a).val().replace(/(^\s*)|(\s*$)/g,"")}function isPhone(a){return/^1[3-5,7-8]{1}[0-9]{9}$/.test(a)||/^([0-9]{3,4}-)?[0-9]{7,8}$/.test(a)}
function showTime(a){a=a.replace(/-/g,"/");a=new Date(a);a=(new Date).getTime()-a.getTime();return 36E5>a?(a=Math.floor(a/6E4),0==a?"\u521a\u521a":a+"\u5206\u949f\u524d"):864E5>a?Math.floor(a/36E5)+"\u5c0f\u65f6\u524d":2592E6>a?Math.floor(a/864E5)+"\u5929\u524d":31104E6>a?Math.floor(a/2592E6)+"\u6708\u524d":"1\u5e74\u524d"}function mORcm(a){return 1>a?Math.round(100*a)+"\u516c\u5206":a+"\u7c73"}
function addcookie(a,b){var c=new Date;c.setTime(c.getTime()+31536E7);document.cookie=a+"="+escape(b)+";expires="+c.toGMTString()+";path=/;domain=cnzhaoshu.com"}function getcookie(a){for(var b=document.cookie.split("; "),c=0;c<b.length;c++){var e=b[c].split("=");if(e[0]==a)return unescape(e[1])}}function delcookie(a){var b=new Date;b.setTime(b.getTime()-1E4);document.cookie=a+"=a;expires="+b.toGMTString()+";path=/;domain=cnzhaoshu.com"}
function login(){if(window.isOpenLogin)try{XD.sendMessage(parent,'{"event":"login"}')}catch(a){}else $.blockUI({message:'<img id="login_qrcode" onclick="$.unblockUI()" src="../img/loging.gif"><div class="login_info">\u8bf7\u7528 \u5fae\u4fe1 \u626b\u63cf\u4e8c\u7ef4\u7801\u767b\u5f55<br><label><input type="checkbox" checked="checked">\u4e0b\u6b21\u81ea\u52a8\u767b\u5f55\uff08\u516c\u7528\u7535\u8111\u4e0a\u4e0d\u8981\u52fe\u9009\uff09</label></div>',css:{border:0,top:"110px",left:($(window).width()-
280)/2+"px",width:"280px",height:"335px"}}),loginQRcode()}function loginQRcode(){var a=(new Date).getTime();$.get("/com/login.qrcode.php?t="+a,function(a){qrcodeTicket=a;0<navigator.userAgent.indexOf("MSIE")?$("#login_qrcode").attr("src","/qrlogin/"+qrcodeTicket.toLowerCase()+".jpg"):$("#login_qrcode").attr("src","http://mp.weixin.qq.com/cgi-bin/showqrcode?ticket="+a);setTimeout(checkLogin,2E3)})}
function checkLogin(){var a=(new Date).getTime(),b=$(".login_info input[type='checkbox']").is(":checked");$.getJSON("/com/login.checkqrcode.php?t="+a,{ticket:qrcodeTicket,autoLogin:b},function(a){a?(user=a,$.unblockUI(),window.location.reload()):setTimeout(checkLogin,2E3)})}
function logout(){delcookie("user2");0<$("#open_home").length?window.location.href=getcookie("open_home2"):0<window.location.href.indexOf("findtree.html")||0<window.location.href.indexOf("mytree.html")?window.location.href=".":window.location.reload()}
function checkUser(){(user=getcookie("user2"))?(user=JSON.parse(user),$("#welcome").html(user.name),$("#logout").show(),$("#login").hide(),isLogin=!0,$.inArray(user.role,[101,9])&&0<window.location.href.indexOf("mytree.html")&&window.location.replace("/qjd.html?shopid="+user.userid)):(user=null,isLogin=!1)}
function search(a,b,c){if(!isLoading){isLoading=!0;window.url_shop_id&&(b="");$.getJSON("/com/search.php",{where:a,limit:b,fromWhere:"pc"},function(a){if(a){for(var b=0;b<a.length;b++){var c=a[b];window.treeid&&window.treeid==c.treeid||addTree(c)}isEnd=a.length<pageItems}else isEnd=!0;a=$("#treelist").children();a=Math.ceil(a.length/columns)*itemHeight+50;$("#treelist").height(a);isLoading=!1;$("#searchmore").hide();if(window.isOpenApi)try{var e=$("#treelist").offset().top,f=a<$(window).height()-
e?$(window).height()-e:a;XD.sendMessage(parent,'{"event":"height","height":'+(f+e)+"}")}catch(g){}});page++;try{setPrice(a,c)}catch(e){}}}
function addTree(a){var b=[];a.dbh&&(a.dbh=parseFloat(a.dbh),a.dbh&&b.push("\u5f84"+a.dbh+"\u516c\u5206"));a.age&&(a.age=parseFloat(a.dbh),a.age&&b.push("\u9f84"+a.age+"\u5e74"));a.crownwidth&&(a.crownwidth=parseFloat(a.crownwidth),a.crownwidth&&b.push("\u51a0"+mORcm(a.crownwidth)));a.height&&(a.height=parseFloat(a.height),a.height&&b.push("\u9ad8"+mORcm(a.height)));a.branch_point_height&&(a.branch_point_height=parseFloat(a.branch_point_height),a.branch_point_height&&b.push("\u5206"+mORcm(a.branch_point_height)));
a.branch_bough_number&&b.push("\u679d"+a.branch_bough_number+"\u4e2a");a.pname&&(a.name="'"+a.pname+"'"+a.name);a.price=Math.round(100*a.price)/100;0==a.price&&(a.price="\u8bae\u4ef7");a.unit||(a.unit="\u682a");a.imgpath=decodeImgpath(a.imgpath);var c="";switch(a.state){case 2:c='<span onmouseover="showHintRenZheng(this)" class="renzheng">\u5df2\u8ba4\u8bc1</span>';break;case 3:c='<span onmouseover="showHintQiJianDian(this)" class="qjd">\u65d7\u8230\u5e97</span>';break;case 4:c='<span onmouseover="showHintQiJianDian(this)" class="qjd">\u5355\u54c1\u738b</span>'}var e=
0<a.collections?' <span class="cangmi">\u85cf\u7c73'+a.collections+"</span>":"",d;d='<div class="imgbox">'+('<img src="/trees/s2/'+a.imgpath[0]+'" /></div>');a.invoice&&(d+='<img class="fapiao" src="/img/fapiao.png?t=2">');a.phototime&&(d+='<p><div class="poi"></div></p>');d+='<p><span class="name">'+a.name+"</span></p>";101==a.type?(d+='<p><span class="place">'+showTime(a.time)+"</span></p>",d+='<p class="size">'+a.remark+"</p>"):(d+='<p><span class="price"><i>\uffe5</i>'+a.price+'</span> <span class="count">'+
a.count+a.unit+"</span></p>",d+='<p><span class="place">'+showTime(a.time)+"</span></p>",d+='<p class="size">'+b.join(" ")+"</p>");d+="<p>"+a.username+"</p>";d+='<p><span class="place">'+a.province+" "+a.district+" "+e+c+"</span></p>";a="tree.html?t=1&tree="+JSON.stringify(a);0<window.location.href.indexOf("findtree.html")&&(a+="&type=findtree");window.isOpenApi?(b=window.isOpenLogin?"&login=1":"",$("#treelist").append($("<a/>").html(d).attr({href:a+b}))):$("#treelist").append($("<a/>").html(d).attr({href:a,
target:"_blank"}))}function showHintRenZheng(a){a=$(a).on("mouseout",function(){$(".hintRenZheng").remove()}).parent().parent().parent();$("<div></div>").html("\u5df2\u5b9e\u5730\u8003\u5bdf<br>\u8ba4\u8bc1\u8d391500").addClass("hintRenZheng").css({left:"0px",bottom:"60px"}).appendTo(a)}
function showHintQiJianDian(a){a=$(a).on("mouseout",function(){$(".hintQiJianDian").remove()}).parent().parent().parent();$("<div></div>").html("\u6709\u884c\u4e1a\u8d44\u8d28\u548c\u89c4\u6a21\u7ecf\u8425<br>\u5e74\u670d\u52a1\u8d391900\u5143").addClass("hintQiJianDian").css({left:"0px",bottom:"60px"}).appendTo(a)}
function onSearch(a,b){a||(a=valueTrim("#key"));a&&(window.isHome?($("#where").html(""),$("#spec_dbh").val(""),$("#spec_crownwidth").val(""),$("#spec_height").val(""),$("#btn_price").html("\u4ef7\u683c\u25c7"),$("#btn_price").attr("class","unselect"),$("#btn_time").attr("class","unselect"),$("#btn_renzheng").attr("class","unselect"),$("#btn_yuantu").attr("class","unselect"),$("#btn_shipin").attr("class","unselect"),$("#group1000").attr("class","unselect"),$("#group1001").attr("class","unselect"),
searchKey(a,null,b),$("#tree").is(":hidden")&&showTree()):(a=b?'where={"key":"'+a+'","exact":1}':"key="+a,window.isOpenApi?(b=getcookie("open_home2"),location.href=b?b+(0<b.indexOf("platform")?"&":"?")+a:"./?"+a):location.href="./?"+a))}
function setHotkey(){if($("#hotkey").length){var a="<a href=\"javascript:onSearch('\u5f20\u8f89')\">\u641c\u82d7\u5703</a><a href=\"javascript:onSearch('13931398852')\">\u641c\u624b\u673a</a>",b;b="\u56fd\u69d0 \u767d\u814a \u6cd5\u6850 \u4e94\u89d2\u67ab \u6cb9\u677e \u94f6\u674f \u6d77\u68e0 \u767d\u76ae\u677e \u7d2b\u53f6\u674e \u91d1\u53f6\u6986".split(" ");for(var c=0;c<b.length;c++)a+="<a href=\"javascript:onSearch('"+b[c]+"')\">"+b[c]+"</a>";$("#hotkey").html(a)}}
function setCart(){user&&$("#cart").length&&$.get("/com/count.cart.php",{userid:user.userid},function(a){$("#cart").html(a).animate({fontSize:"110px",lineHeight:"0"}).animate({fontSize:"32px",lineHeight:"80%"}).click(function(){window.location="findtree.html"})})}
function setOpenApi(){urlRequest("platform")&&(window.platform=urlRequest("platform"));urlRequest("union")&&(window.union=urlRequest("union"));if(urlRequest("name"))document.title=urlRequest("name");else if(window.platform)switch(parseInt(platform)){case 1E3:document.title="\u5317\u4eac\u82d7\u6728";break;case 1001:document.title="\u5317\u4eac\u5e02\u56ed\u6797\u7eff\u5316\u884c\u4e1a\u534f\u4f1a"}urlRequest("login")?window.isOpenLogin=!0:$(".login").show();window.isHome?addcookie("open_home2",window.location.href):
$("#open_home").attr("href",getcookie("open_home2"));var a=window.isOpenLogin?"?login=1":"";$("#open_mytree").attr("href","mytree.html"+a);$("#open_findtree").attr("href","findtree.html"+a);XD.receiveMessage(function(a){if("string"==typeof a)switch(a=JSON.parse(a),a.event){case "search":if(isEnd||isLoading||0<$("#treeview").length||!isPc&&0<$("#userlist").length&&"none"!=$("#userlist").css("display"))break;$("#searchmore").show();search(getWhere(),getLimit());break;case "key":onSearch(a.key)}})}checkUser();
setCart();window.isOpenApi?setOpenApi():setHotkey();$("#key").keydown(function(a){13==a.keyCode&&onSearch()});