var dot_visitor=doT.template($("#dot_visitor").text()),dot_collector=doT.template($("#dot_collector").text()),dot_showinfo=doT.template($("#dot_showinfo").text()),MEMBER_LI_HEIGHT=70,MEMBER_COLUMN=3,isLoadingMember=!1,isEndMember=!1,isLoadingMember1=!1,isEndMember1=!1,isLoadingMember2=!1,isEndMember2=!1,isLoadingMember3=!1,isEndMember3=!1,shopname,allcount,phone="",user={};function string2shortTime(a){return a?(a=a.replace(/-/g,"/"),a=(new Date(a)).getTime(),ms2shortTime(a)):"\u521a\u521a"}
function ms2shortTime(a){a=(new Date).getTime()-a;return 36E5>a?(a=Math.floor(a/6E4),0==a?"\u521a\u521a":a+"\u5206\u949f\u524d"):864E5>a?Math.floor(a/36E5)+"\u5c0f\u65f6\u524d":2592E6>a?Math.floor(a/864E5)+"\u5929\u524d":31104E6>a?Math.floor(a/2592E6)+"\u6708\u524d":"1\u5e74\u524d"}var userid=getQueryString("userid");
userid?(user.userid=userid,loadshopuser()):(user=getcookie("user2"))?(user=JSON.parse(user),shopname=user.shopname,$("#gomyshop").attr("href","http://cnzhaoshu.com/shop.php?userid="+user.userid),$("#zt_name").html(user.name),user.phone&&(phone=user.phone),$("#zt_tel").html(phone),$("#zt_lo").attr("src","/headimg/0/"+user.userid+".jpg?v="+user.version)):window.location.replace("m.php");$(".zsq_box").height($(window).height());
$(".sideMenu ul .slide_li .zb_item").click(function(){var a=$(this).parent().find(".l_main1").height()+54;if($(this).hasClass("on"))$(this).removeClass("on"),$(".sideMenu ul .slide_li").animate({height:"54px"}),$(".zsq_box").height($(window).height());else{$(".sideMenu ul .slide_li .zb_item").removeClass("on");$(this).addClass("on");var b=$(this).attr("draworder");-1==b?$(this).parent().animate({height:a}):1==b?loadMember3("0,12"):2==b?loadMember2("0,12"):3==b?loadMember1("0,12"):4==b&&loadMember("0,12");
$(this).parent().siblings().animate({height:"54px"});$(".zsq_box").height("auto")}});function onerrorHeadimg(){var a=window.event||arguments.callee.caller.arguments[0];(a.currentTarget||a.srcElement||a.target).src="http://cnzhaoshu.com/headimg/96/1.jpg"}
function loadshopuser(){$.getJSON("/com/search.myshopinfo.php",{userid:user.userid},function(a){$("#gomyshop").attr("href","http://cnzhaoshu.com/shop.php?userid="+user.userid);$("#zt_name").html(a.name);a.phone&&(phone=a.phone);$("#zt_tel").html(phone);$("#zt_lo").attr("src","/headimg/0/"+user.userid+".jpg?v="+user.version);shopname=a.name;user.shopid=a.shopid})}
Date.prototype.date=function(){var a=this.getMonth()+1,b=this.getDate();10>a&&(a="0"+a);10>b&&(b="0"+b);return this.getFullYear()+"-"+a+"-"+b};
$.getJSON("/com/search.zsq_record.php",{userid:user.userid},function(a){a?a.today!=(new Date).date()&&(a.today_visit=0,a.today_collect=0,a.today_share=0,a.today_mycollect=0):(allcount=0,a={today_visit:0,allvisit:0,today_collect:0,allcollect:0,today_share:0,allshare:0,today_mycollect:0,allmycollect:0});$("#visitnow").html("\u4eca\u65e5\u8bbf\u95ee"+a.today_visit);$("#visitall").html("\u603b\u8bbf\u95ee"+a.allvisit);$("#collectnow").html("\u4eca\u65e5\u6536\u85cf"+a.today_collect);$("#collectall").html("\u603b\u6536\u85cf"+
a.allcollect);$("#sharenow").html("\u4eca\u65e5\u5206\u4eab"+a.today_share);$("#shareall").html("\u603b\u5206\u4eab"+a.allshare);$("#mycollectnow").html("\u4eca\u65e5\u6536\u85cf"+a.today_mycollect);$("#mycollectall").html("\u603b\u6536\u85cf"+a.allmycollect);allcount=a.allcollect+a.allshare+a.allvisit});$("#visitshop").scroll(function(){if(!isLoadingMember&&!isEndMember){var a=$(this)[0].scrollHeight,b=$(this)[0].scrollTop,c=$(this).height();b+c>=a-100&&loadMember()}});
$("#shareshop").scroll(function(){if(!isLoadingMember1&&!isEndMember1){var a=$(this)[0].scrollHeight,b=$(this)[0].scrollTop,c=$(this).height();b+c>=a-100&&loadMember1()}});$("#collectshop").scroll(function(){if(!isLoadingMember2&&!isEndMember2){var a=$(this)[0].scrollHeight,b=$(this)[0].scrollTop,c=$(this).height();b+c>=a-100&&loadMember2()}});
$("#mycollect").scroll(function(){if(!isLoadingMember3&&!isEndMember3){var a=$(this)[0].scrollHeight,b=$(this)[0].scrollTop,c=$(this).height();b+c>=a-100&&loadMember3()}});
function loadMember(a){if(!isLoadingMember){isLoadingMember=!0;var b=Math.ceil(210/MEMBER_LI_HEIGHT+1)*MEMBER_COLUMN;a=a?a:$("#visitshop a").length+","+b;var c=$("#visitshop").height();$.getJSON("/com/search.visitshop.php",{userid:user.userid,limit:a},function(a){a?($("#visitshop").append(dot_visitor(a)),100>c&&(a=$("#visitshop").height()+54,$("#visitshop").parent().animate({height:a}),$("#visitshop").parent().find(".zb_item").attr("draworder","-1"))):isEndMember=!0;isLoadingMember=!1})}}
function loadMember1(a){if(!isLoadingMember1){isLoadingMember1=!0;var b=Math.ceil(210/MEMBER_LI_HEIGHT+1)*MEMBER_COLUMN;a=a?a:$("#shareshop a").length+","+b;var c=$("#shareshop").height();$.getJSON("/com/search.shareshop.php",{userid:user.userid,limit:a},function(a){a?($("#shareshop").append(dot_visitor(a)),100>c&&(a=$("#shareshop").height()+54,$("#shareshop").parent().animate({height:a}),$("#shareshop").parent().find(".zb_item").attr("draworder","-1"))):isEndMember1=!0;isLoadingMember1=!1})}}
function loadMember2(a){if(!isLoadingMember2){isLoadingMember2=!0;var b=Math.ceil(210/MEMBER_LI_HEIGHT+1)*MEMBER_COLUMN;a=a?a:$("#collectshop a").length+","+b;var c=$("#collectshop").height();$.getJSON("/com/search.collectshop.php",{shopid:user.shopid,limit:a},function(a){if(a){for(var b=0;b<a.length;b++)a[b].shopid=user.shopid;$("#collectshop").append(dot_collector(a));100>c&&(a=$("#collectshop").height()+54,$("#collectshop").parent().animate({height:a}),$("#collectshop").parent().find(".zb_item").attr("draworder",
"-1"))}else isEndMember2=!0;isLoadingMember2=!1})}}
function loadMember3(a){if(!isLoadingMember3){isLoadingMember3=!0;var b=Math.ceil(210/MEMBER_LI_HEIGHT+1)*MEMBER_COLUMN;a=a?a:$("#mycollect a").length+","+b;var c=$("#mycollect").height();$.getJSON("/com/search.mycollectshop.php",{userid:user.userid,limit:a},function(a){a?($("#mycollect").append(dot_collector(a)),100>c&&(a=$("#mycollect").height()+54,$("#mycollect").parent().animate({height:a}),$("#mycollect").parent().find(".zb_item").attr("draworder","-1"))):isEndMember3=!0;isLoadingMember3=!1})}}
$("#shareshop").on("click",".showmore",function(){var a=$(this).attr("dateid");$.getJSON("/com/search.shareinfo.php",{visitorid:a,userid:user.userid},function(a){$("#showinfo").html(dot_showinfo(a));$(".way").html("\u5206\u4eab\u4e86\u6211!");$(".topshow").show()})});
$("#visitshop").on("click",".showmore",function(){var a=$(this).attr("dateid");$.getJSON("/com/search.visitinfo.php",{visitorid:a,userid:user.userid},function(a){$("#showinfo").html(dot_showinfo(a));$(".way").html("\u8bbf\u95ee\u4e86\u6211!");$(".topshow").show()})});$(".alert_btn").click(function(){$(".topshow").hide()});function getcookie(a){for(var b=document.cookie.split("; "),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0]==a)return unescape(d[1])}}
function getQueryString(a){a=new RegExp("(^|&)"+a+"=([^&]*)(&|$)","i");a=window.location.search.substr(1).match(a);return null!=a?unescape(a[2]):null}function getTitle(){return shopname+"\u7684\u627e\u6811\u5708"}function getImageUrl(){return"http://www.cnzhaoshu.com/headimg/96/"+user.userid+".jpg?v="+user.version}function getLink(){return"http://www.cnzhaoshu.com/zsq.php?userid="+user.userid}
function getDescription(){return"\u5df2\u7ecf\u6709"+allcount+"\u4eba\u5077\u5077\u559c\u6b22\u6211\u4e86\uff01"}
function prepareShare(){wx.onMenuShareAppMessage({title:getTitle(),desc:getDescription(),link:getLink(),imgUrl:getImageUrl()});wx.onMenuShareTimeline({title:getTitle()+"\n"+getDescription(),link:getLink(),imgUrl:getImageUrl()});wx.onMenuShareQQ({title:getTitle(),desc:getDescription(),link:getLink(),imgUrl:getImageUrl()});wx.onMenuShareWeibo({title:getTitle(),desc:getDescription(),link:getLink(),imgUrl:getImageUrl()})}
function setWechatJSSDK(a){wx.config({debug:!1,appId:a.appId,timestamp:a.timestamp,nonceStr:a.nonceStr,signature:a.signature,jsApiList:"onMenuShareTimeline onMenuShareAppMessage onMenuShareQQ onMenuShareQZone onMenuShareWeibo hideMenuItems".split(" ")});wx.ready(function(){wx.hideMenuItems({menuList:["menuItem:copyUrl"]});prepareShare()})}function loadWechatJSSDK(){$.getJSON("/com/wechat.jssdk.php?url="+encodeURIComponent(location.href.split("#")[0]),function(a){setWechatJSSDK(a)})}
setTimeout(loadWechatJSSDK,500);